
name: build documentation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Python details
        run: |
          python3 --version
          which python3
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run pdoc3
        run: tox -e doc
      - name: Commit new data
        uses: EndBug/add-and-commit@v7.1.0
        env:
          COMMIT_MSG: GH Action build documentation
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: ${{ env.COMMIT_MSG }}
          add: 'docs/*'
          branch: 'docs'
          push: true
          pull_strategy: '--no-rebase'
